## DO-MS command line configuration
## for use with do-ms_cmd.R

verbose: true

## Input/Output

# paths to folders with MaxQuant txt output
input_folders:
  - /gd/MS/SCoPE/phospho/dat/PS095
  - /gd/MS/SCoPE/phospho/dat/PS096
  
# match up with the input_files list in global.R
input_files:
  - evidence
  - msms
  - msmsScans
  - allPeptides
  - parameters
  
# match up with misc_input_files list in global.R
#misc_input_files:
#  inclusion_list: /path/to/inclusion_list.txt

output: /Users/albert/Desktop/report.html

## Filters

# regular expressions to match raw file names against
include_files: PS096
exclude_files: PS096D

# custom names for files
exp_names:
  - Control
  - '2X'
  - '4X'
  - '10X'
  - 'this shouldnt show'

pep_thresh: 0.01
remove_decoy: REV_
remove_contam: CON_

## Figure rendering options

ppi: 150

# label font size
figure_title_font_size: 16
# axis tick label font size
figure_axis_font_size: 12
# facet label font size
figure_facet_font_size: 12
# line width
figure_line_width: 1
# show background grid
figure_show_grid: true

## Report options

# choices: pdf, html
report_format: html

# choices: default, cerulean, flatly, darkly, readable, 
# spacelab, united, cosmo, lumen, paper, sandstone, simplex, yeti
# previews: https://bootswatch.com/3/
report_theme: readable

# figure size (in inches)
report_figure_width: 5
report_figure_height: 5

# figure format. choices: pdf, png
report_figure_format: png


