## DO-MS command line configuration
## for use with do-ms_cmd.R

## Input/Output

# paths to folders with MaxQuant txt output
input_folders:
  - /path/to/MaxQuant/output/a
  - /path/to/MaxQuant/output/b
  - /path/to/MaxQuant/output/c
  
# files to load from each folder
load_input_files:
  - evidence
  - msms
  - msmsScans
  - allPeptides
  - summary
  - parameters
  
# match up with misc_input_files list in global.R
#misc_input_files:
#  inclusion_list: /path/to/inclusion_list.txt

output: /path/to/report.html

## Filters

# regular expressions to match raw file names against
include_files: '180614_S'
exclude_files: '180614_S_A'

# experiment name format string
# %i -- index of raw file
# %f -- folder name
# %e -- raw file name
exp_name_format: 'Exp %f %i'

# optional regular expression pattern to extract
# from the experiment names after applying the format string
exp_name_pattern: '[0-9]{6}'

# custom names for files
exp_names:
  - Control
  - '2X'
  - '4X'
  - '10X'
  
# custom order for files
exp_order: [4,2,3,1]

pep_thresh: 0.01
pif_thresh: 0.7
remove_decoy: REV_
remove_contam: CON_

## Figure rendering options

ppi: 150

# label font size
figure_title_font_size: 16
# axis tick label font size
figure_axis_font_size: 12
# facet label font size
figure_facet_font_size: 12
# line width
figure_line_width: 1
# show background grid
figure_show_grid: true

## Report options

# choices: pdf, html
report_format: html

# choices: default, cerulean, flatly, darkly, readable, 
# spacelab, united, cosmo, lumen, paper, sandstone, simplex, yeti
# previews: https://bootswatch.com/3/
report_theme: readable

# figure size (in inches)
report_figure_width: 5
report_figure_height: 5

# figure format. choices: pdf, png
report_figure_format: png


